version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - server

networks:
  my_network:
